export const INCREMENT_COUPON_COUNT = 'INCREMENT_COUPON_COUNT';
export const ADD_NEW_UPGRADE = 'ADD_NEW_UPGRADE';
export const REMOVE_UPGRADE = 'REMOVE_UPGRADE';
export const SUBTRACT_COUPON_AMOUNT = 'SUBTRACT_COUPON_AMOUNT';
export const ADD_COUPON_AMOUNT = 'ADD_COUPON_AMOUNT';
