export const UPGRADE_COUPON_BOOK = 'UPGRADE_COUPON_BOOK';
export const UPGRADE_COUPON_STAMP = 'UPGRADE_COUPON_STAMP';
export const UPGRADE_COUPON_PRINTER = 'UPGRADE_COUPON_PRINTER';
export const UPGRADE_COUPON_STORE = 'UPGRADE_COUPON_STORE';
export const UPGRADE_COUPON_FACTORY = 'UPGRADE_COUPON_FACTORY';

export const UPGRADE_COUPON_BOOK_COST = 10;
export const UPGRADE_COUPON_STAMP_COST = 50;
export const UPGRADE_COUPON_PRINTER_COST = 100;
export const UPGRADE_COUPON_STORE_COST = 200;
export const UPGRADE_COUPON_FACTORY_COST = 500;

export const COUPON_UPGRADE_COST_DICTIONARY = {
	[UPGRADE_COUPON_BOOK]: UPGRADE_COUPON_BOOK_COST,
	[UPGRADE_COUPON_STAMP]: UPGRADE_COUPON_STAMP_COST,
	[UPGRADE_COUPON_PRINTER]: UPGRADE_COUPON_PRINTER_COST,
	[UPGRADE_COUPON_STORE]: UPGRADE_COUPON_STORE_COST,
	[UPGRADE_COUPON_FACTORY]: UPGRADE_COUPON_FACTORY_COST
};
