export const UPGRADE_COUPON_BOOK = 'UPGRADE_COUPON_BOOK';
export const UPGRADE_COUPON_STAMP = 'UPGRADE_COUPON_STAMP';
export const UPGRADE_COUPON_PRINTER = 'UPGRADE_COUPON_PRINTER';
export const UPGRADE_COUPON_STORE = 'UPGRADE_COUPON_STORE';
export const UPGRADE_COUPON_FACTORY = 'UPGRADE_COUPON_FACTORY';
