export const UPGRADE_COUPON_BOOK = 'UPGRADE_COUPON_BOOK';
export const UPGRADE_COUPON_STAMP = 'UPGRADE_COUPON_STAMP';
export const UPGRADE_COUPON_PRINTER = 'UPGRADE_COUPON_PRINTER';
export const UPGRADE_COUPON_STORE = 'UPGRADE_COUPON_STORE';
export const UPGRADE_COUPON_FACTORY = 'UPGRADE_COUPON_FACTORY';
export const UPGRADE_COUPON_CORPORATION = 'UPGRADE_COUPON_CORPORATION';
export const UPGRADE_RUSTY_SCISSORS = 'UPGRADE_RUSTY_SCISSORS';
export const UPGRADE_GOOD_SCISSORS = 'UPGRADE_GOOD_SCISSORS';
export const UPGRADE_AMBIDEXTROUS_SCISSORS = 'UPGRADE_AMBIDEXTROUS_SCISSORS';
export const UPGRADE_INDUSTRIAL_SCISSORS = 'UPGRADE_INDUSTRIAL_SCISSORS';
export const UPGRADE_CEREMONIAL_SCISSORS = 'UPGRADE_CEREMONIAL_SCISSORS';
export const UPGRADE_SLIGHT_MAGIC_SCISSORS = 'UPGRADE_SLIGHT_MAGIC_SCISSORS';
export const UPGRADE_MYTHICAL_SCISSORS = 'UPGRADE_MYTHICAL_SCISSORS';

export const UPGRADE_COUPON_BOOK_COST = 299;
export const UPGRADE_COUPON_STAMP_COST = 799;
export const UPGRADE_COUPON_PRINTER_COST = 2499;
export const UPGRADE_COUPON_STORE_COST = 29999;
export const UPGRADE_COUPON_FACTORY_COST = 99999;
export const UPGRADE_COUPON_CORPORATION_COST = 849999;

//rates for exponential price increase
export const UPGRADE_COUPON_BOOK_INCREASE = 5.2;
export const UPGRADE_COUPON_STAMP_INCREASE = 15.6;
export const UPGRADE_COUPON_PRINTER_INCREASE = 62.8;
export const UPGRADE_COUPON_STORE_INCREASE = 223.3;
export const UPGRADE_COUPON_FACTORY_INCREASE = 649.7;
export const UPGRADE_COUPON_CORPORATION_INCREASE = 1224.5;

export const UPGRADE_RUSTY_SCISSORS_COST = 24;
export const UPGRADE_GOOD_SCISSORS_COST = 199;
export const UPGRADE_AMBIDEXTROUS_SCISSORS_COST = 999;
export const UPGRADE_INDUSTRIAL_SCISSORS_COST = 4499;
export const UPGRADE_CEREMONIAL_SCISSORS_COST = 11999;
export const UPGRADE_SLIGHT_MAGIC_SCISSORS_COST = 84999;
export const UPGRADE_MYTHICAL_SCISSORS_COST = 399999;

export const UPGRADE_RUSTY_SCISSORS_INCREASE = 1.5;
export const UPGRADE_GOOD_SCISSORS_INCREASE = 3.8;
export const UPGRADE_AMBIDEXTROUS_SCISSORS_INCREASE = 9.2;
export const UPGRADE_INDUSTRIAL_SCISSORS_INCREASE = 25.6;
export const UPGRADE_CEREMONIAL_SCISSORS_INCREASE = 100.3;
export const UPGRADE_SLIGHT_MAGIC_SCISSORS_INCREASE = 250.7;
export const UPGRADE_MYTHICAL_SCISSORS_INCREASE = 800.4;

export const UPGRADE_COUPON_BOOK_ADDS = 1;
export const UPGRADE_COUPON_STAMP_ADDS = 3;
export const UPGRADE_COUPON_PRINTER_ADS = 5;
export const UPGRADE_COUPON_STORE_ADDS = 10;
export const UPGRADE_COUPON_FACTORY_ADDS = 50;
export const UPGRADE_COUPON_CORPORATION_ADDS = 100;

export const UPGRADE_RUSTY_SCISSORS_ADDS = 0.25;
export const UPGRADE_GOOD_SCISSORS_ADDS = 0.8;
export const UPGRADE_AMBIDEXTROUS_SCISSORS_ADDS = 1.5;
export const UPGRADE_INDUSTRIAL_SCISSORS_ADDS = 6;
export const UPGRADE_CEREMONIAL_SCISSORS_ADDS = 25;
export const UPGRADE_SLIGHT_MAGIC_SCISSORS_ADDS = 90;
export const UPGRADE_MYTHICAL_SCISSORS_ADDS = 280;

export const COUPONS_PER_CLICK_SECTION_MINIMUM = 19;
export const COUPONS_PER_SECOND_SECTION_MINIMUM = 299;

export const COUPON_UPGRADE_BASE_COST_DICTIONARY = {
	[UPGRADE_COUPON_BOOK]: UPGRADE_COUPON_BOOK_COST,
	[UPGRADE_COUPON_STAMP]: UPGRADE_COUPON_STAMP_COST,
	[UPGRADE_COUPON_PRINTER]: UPGRADE_COUPON_PRINTER_COST,
	[UPGRADE_COUPON_STORE]: UPGRADE_COUPON_STORE_COST,
	[UPGRADE_COUPON_FACTORY]: UPGRADE_COUPON_FACTORY_COST,
	[UPGRADE_COUPON_CORPORATION]: UPGRADE_COUPON_CORPORATION_COST,
	[UPGRADE_RUSTY_SCISSORS]: UPGRADE_RUSTY_SCISSORS_COST,
	[UPGRADE_GOOD_SCISSORS]: UPGRADE_GOOD_SCISSORS_COST,
	[UPGRADE_AMBIDEXTROUS_SCISSORS]: UPGRADE_AMBIDEXTROUS_SCISSORS_COST,
	[UPGRADE_INDUSTRIAL_SCISSORS]: UPGRADE_INDUSTRIAL_SCISSORS_COST,
	[UPGRADE_CEREMONIAL_SCISSORS]: UPGRADE_CEREMONIAL_SCISSORS_COST,
	[UPGRADE_SLIGHT_MAGIC_SCISSORS]: UPGRADE_SLIGHT_MAGIC_SCISSORS_COST,
	[UPGRADE_MYTHICAL_SCISSORS]: UPGRADE_MYTHICAL_SCISSORS_COST
};

export const COUPON_UPGRADE_COST_DICTIONARY = {
	[UPGRADE_COUPON_BOOK]: UPGRADE_COUPON_BOOK_COST,
	[UPGRADE_COUPON_STAMP]: UPGRADE_COUPON_STAMP_COST,
	[UPGRADE_COUPON_PRINTER]: UPGRADE_COUPON_PRINTER_COST,
	[UPGRADE_COUPON_STORE]: UPGRADE_COUPON_STORE_COST,
	[UPGRADE_COUPON_FACTORY]: UPGRADE_COUPON_FACTORY_COST,
	[UPGRADE_COUPON_CORPORATION]: UPGRADE_COUPON_CORPORATION_COST,
	[UPGRADE_RUSTY_SCISSORS]: UPGRADE_RUSTY_SCISSORS_COST,
	[UPGRADE_GOOD_SCISSORS]: UPGRADE_GOOD_SCISSORS_COST,
	[UPGRADE_AMBIDEXTROUS_SCISSORS]: UPGRADE_AMBIDEXTROUS_SCISSORS_COST,
	[UPGRADE_INDUSTRIAL_SCISSORS]: UPGRADE_INDUSTRIAL_SCISSORS_COST,
	[UPGRADE_CEREMONIAL_SCISSORS]: UPGRADE_CEREMONIAL_SCISSORS_COST,
	[UPGRADE_SLIGHT_MAGIC_SCISSORS]: UPGRADE_SLIGHT_MAGIC_SCISSORS_COST,
	[UPGRADE_MYTHICAL_SCISSORS]: UPGRADE_MYTHICAL_SCISSORS_COST
};

export const COUPON_UPGRADE_INCREASE_DICTIONARY = {
	[UPGRADE_COUPON_BOOK]: UPGRADE_COUPON_BOOK_INCREASE,
	[UPGRADE_COUPON_STAMP]: UPGRADE_COUPON_STAMP_INCREASE,
	[UPGRADE_COUPON_PRINTER]: UPGRADE_COUPON_PRINTER_INCREASE,
	[UPGRADE_COUPON_STORE]: UPGRADE_COUPON_STORE_INCREASE,
	[UPGRADE_COUPON_FACTORY]: UPGRADE_COUPON_FACTORY_INCREASE,
	[UPGRADE_COUPON_CORPORATION]: UPGRADE_COUPON_CORPORATION_INCREASE,
	[UPGRADE_RUSTY_SCISSORS]: UPGRADE_RUSTY_SCISSORS_INCREASE,
	[UPGRADE_GOOD_SCISSORS]: UPGRADE_GOOD_SCISSORS_INCREASE,
	[UPGRADE_AMBIDEXTROUS_SCISSORS]: UPGRADE_AMBIDEXTROUS_SCISSORS_INCREASE,
	[UPGRADE_INDUSTRIAL_SCISSORS]: UPGRADE_INDUSTRIAL_SCISSORS_INCREASE,
	[UPGRADE_CEREMONIAL_SCISSORS]: UPGRADE_CEREMONIAL_SCISSORS_INCREASE,
	[UPGRADE_SLIGHT_MAGIC_SCISSORS]: UPGRADE_SLIGHT_MAGIC_SCISSORS_INCREASE,
	[UPGRADE_MYTHICAL_SCISSORS]: UPGRADE_MYTHICAL_SCISSORS_INCREASE
}

export const COUPON_UPGRADE_ADDS_DICTIONARY = {
	[UPGRADE_COUPON_BOOK]: UPGRADE_COUPON_BOOK_ADDS,
	[UPGRADE_COUPON_STAMP]: UPGRADE_COUPON_STAMP_ADDS,
	[UPGRADE_COUPON_PRINTER]: UPGRADE_COUPON_PRINTER_ADS,
	[UPGRADE_COUPON_STORE]: UPGRADE_COUPON_STORE_ADDS,
	[UPGRADE_COUPON_FACTORY]: UPGRADE_COUPON_FACTORY_ADDS,
	[UPGRADE_COUPON_CORPORATION]: UPGRADE_COUPON_CORPORATION_ADDS,
	[UPGRADE_RUSTY_SCISSORS]: UPGRADE_RUSTY_SCISSORS_ADDS,
	[UPGRADE_GOOD_SCISSORS]: UPGRADE_GOOD_SCISSORS_ADDS,
	[UPGRADE_AMBIDEXTROUS_SCISSORS]: UPGRADE_AMBIDEXTROUS_SCISSORS_ADDS,
	[UPGRADE_INDUSTRIAL_SCISSORS]: UPGRADE_INDUSTRIAL_SCISSORS_ADDS,
	[UPGRADE_CEREMONIAL_SCISSORS]: UPGRADE_CEREMONIAL_SCISSORS_ADDS,
	[UPGRADE_SLIGHT_MAGIC_SCISSORS]: UPGRADE_SLIGHT_MAGIC_SCISSORS_ADDS,
	[UPGRADE_MYTHICAL_SCISSORS]: UPGRADE_MYTHICAL_SCISSORS_ADDS
};
